# fly.toml app configuration file generated for kalpoly on 2023-10-14T13:07:13-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kalpoly"
primary_region = "qro"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
